### ISSUE TITLE
Find better way to implement loop on header

### ISSUE THREAD

**Issue by Schwarzam** [Schwarzam/rastronomy#1]
There should be a better way to parse the header instead of going through blocks of 2880 bytes.

There are two problems:

- If the header does not have a END card it goes on the loop until the end of the buffer (than I think it raises an error).
- When it reaches 35 on the counter, it adds the card to the header, if the card is a CONTINUE card, this will raise unknown problems.

Snippets with suggestions: 

```rust
let mut buffer= [0; 2880];
let n = file.read(&mut buffer[..])?;
let mut last_card : Option<Card> = None;

let mut counter = 0; // This is not right!
for card in buffer.chunks(80) { // This for should be replaced by a loop. 
    let card_str = String::from_utf8_lossy(card).trim_end().to_string();
```

```rust
else {
    last_card = Card::parse_card(card_str);
    
    if (counter) == (2880 / 80) - 1 { // Remove this if block
        self.add_card(last_card);
        break;
    }
}
counter += 1; // Remove
```

**Comment by Vincas2539** [comment]
Solved moving last_cart out of the outter loop.
